version = 1

test_patterns = [
    "*tests/**",
    "*/__tests__/**"
]

exclude_patterns = ["migrations/**"]

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "Dockerfile",
    "services/client/Dockerfile",
    "services/db/Dockerfile",
    "services/server/Dockerfile"
  ]

  trusted_registries = [
    "registry.hub.docker.com",
    "registry.gitlab.com"
  ]
