image: docker:stable

stages:
  - build
  - test
  - deploy-development
  - deploy-staging
  - deploy-production

variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

build:server:
  stage: build
  except:
    refs:
      - master
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:server-latest || true
  script:
    - docker build
      --cache-from $IMAGE:server-latest
      --tag $IMAGE:server-latest
      --file ./services/server/Dockerfile
      ./services/server
  after_script:
    - docker push $IMAGE:server-latest

build:client:
  stage: build
  except:
    refs:
      - master
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    REACT_APP_USERS_SERVICE_URL: http://localhost:8001
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:client-latest || true
  script:
    - docker build
      --cache-from $IMAGE:client-latest
      --tag $IMAGE:client-latest
      --file ./services/client/Dockerfile
      ./services/client
  after_script:
    - docker push $IMAGE:client-latest

test:server:
  stage: test
  except:
    refs:
      - master
  image: $IMAGE:server-latest
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    DATABASE_TEST_URL: postgresql://postgres:postgres@postgres:5432/test
    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/test
    FLASK_ENV: testing
    PORT: 5000
  before_script:
    - apk update
    - apk add bash curl
  script:
    - pytest -c /usr/src/app/app/tests/pytest.ini
  after_script:
    - bash <(curl -s https://codecov.io/bash)

deploy-development:server:
  stage: deploy-development
  except:
    refs:
      - master
      - staging
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    HEROKU_APP_NAME: rinnegan-server-development
    HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
  before_script:
    - apk add --no-cache curl
    - chmod +x ./bin/deploy.sh
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:server-latest || true
    - docker tag $IMAGE:server-latest $HEROKU_REGISTRY_IMAGE
    - docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
    - docker push $HEROKU_REGISTRY_IMAGE
    - ./bin/deploy.sh

deploy-development:client:
  stage: deploy-development
  except:
    refs:
      - master
      - staging
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    HEROKU_APP_NAME: rinnegan-client-development
    HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
  before_script:
    - apk add --no-cache curl
    - chmod +x ./bin/deploy.sh
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:client-latest || true
    - docker tag $IMAGE:client-latest $HEROKU_REGISTRY_IMAGE
    - docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
    - docker push $HEROKU_REGISTRY_IMAGE
    - ./bin/deploy.sh

deploy-staging:server:
  stage: deploy-staging
  only:
    refs:
      - staging
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    HEROKU_APP_NAME: rinnegan-server-staging
    HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
  before_script:
    - apk add --no-cache curl
    - chmod +x ./bin/deploy.sh
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:server-latest || true
    - docker tag $IMAGE:server-latest $IMAGE:server-staging
    - docker push $IMAGE:server-staging
    - docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
    - docker tag $IMAGE:server-latest $HEROKU_REGISTRY_IMAGE
    - docker push $HEROKU_REGISTRY_IMAGE
    - ./bin/deploy.sh

deploy-staging:client:
  stage: deploy-staging
  only:
    refs:
      - staging
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    HEROKU_APP_NAME: rinnegan-client-staging
    HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
  before_script:
    - apk add --no-cache curl
    - chmod +x ./bin/deploy.sh
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:client-latest || true
    - docker tag $IMAGE:client-latest $IMAGE:client-staging
    - docker push $IMAGE:client-staging
    - docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
    - docker tag $IMAGE:client-latest $HEROKU_REGISTRY_IMAGE
    - docker push $HEROKU_REGISTRY_IMAGE
    - ./bin/deploy.sh

deploy-production:server:
  stage: deploy-production
  only:
    refs:
      - master
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    HEROKU_APP_NAME: rinnegan-server-production
    HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
  before_script:
    - apk add --no-cache curl
    - chmod +x ./bin/deploy.sh
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:server-latest || true
    - docker tag $IMAGE:server-latest $IMAGE:server-staging
    - docker push $IMAGE:server-staging
    - docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
    - docker tag $IMAGE:server-latest $HEROKU_REGISTRY_IMAGE
    - docker push $HEROKU_REGISTRY_IMAGE
    - ./bin/deploy.sh
    - docker tag $IMAGE:server-staging $IMAGE:server
    - echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker tag $IMAGE:server-latest $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:server
    - docker push $IMAGE:server

deploy-production:client:
  stage: deploy-production
  only:
    refs:
      - master
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    HEROKU_APP_NAME: rinnegan-client-production
    HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
  before_script:
    - apk add --no-cache curl
    - chmod +x ./bin/deploy.sh
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:client-latest || true
    - docker tag $IMAGE:client-latest $IMAGE:client-staging
    - docker push $IMAGE:client-staging
    - docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
    - docker tag $IMAGE:client-latest $HEROKU_REGISTRY_IMAGE
    - docker push $HEROKU_REGISTRY_IMAGE
    - ./bin/deploy.sh
    - docker tag $IMAGE:client-staging $IMAGE:client
    - echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker tag $IMAGE:client-latest $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:client
    - docker push $IMAGE:client
