image: docker:stable

stages:
  - build
  - test
  - deploy

variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

build:database:
  stage: build
  except:
    refs:
      - master
      - staging
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:database || true
  script:
    - docker build
      --cache-from $IMAGE:database
      --tag $IMAGE:database
      --file ./services/db/Dockerfile
      ./services/db
  after_script:
    - docker push $IMAGE:database

build:serverdevelopment:
  stage: build
  except:
    refs:
      - master
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:serverdevelopment || true
  script:
    - docker build
      --cache-from $IMAGE:serverdevelopment
      --tag $IMAGE:serverdevelopment
      --file ./services/server/Dockerfile
      ./services/server
  after_script:
    - docker push $IMAGE:serverdevelopment

test:server:
  stage: test
  except:
    refs:
      - master
  image: $IMAGE:serverdevelopment
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    DATABASE_TEST_URL: postgresql://postgres:postgres@postgres:5432/test
    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/test
    FLASK_ENV: testing
  before_script:
    - apt-get update
    - apt-get install -y curl
  script:
    - black --check --config /usr/src/app/pyproject.toml /usr/src/app
    - flake8 --config /usr/src/app/setup.cfg /usr/src/app
    - isort --atomic --case-sensitive --check-only --force-alphabetical-sort-within-sections --force-single-line-imports --lines-after-imports 2 --lines-between-types 1 --line-width 79 --recursive /usr/src/app
    - pytest -c /usr/src/app/app/tests/pytest.ini
  after_script:
    - bash <(curl -s https://codecov.io/bash)

deploy:serverstaging:
  stage: deploy
  only:
    refs:
      - staging
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    HEROKU_APP_NAME: rinnegan-staging
    HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
  before_script:
    - apk add --no-cache curl
    - docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
  script:
    - docker build
      --tag $HEROKU_REGISTRY_IMAGE
      --file ./services/server/prod.Dockerfile
      ./services/server
    - chmod +x ./bin/deploy.sh
    - docker push $HEROKU_REGISTRY_IMAGE
  after_script:
    - ./bin/deploy.sh
