image: docker:stable

stages:
  - build

variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

build:
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:db || true
  script:
    - docker build
      --cache-from $IMAGE:db
      --tag $IMAGE:db
      --file ./services/db/Dockerfile
      --build-arg SECRET_KEY=$SECRET_KEY
      "./services/db"
  after_script:
    - docker push $IMAGE:db
