version: "3.7"

networks:
  backend:
    driver: bridge
    name: sentimental-backend

  frontend:
    driver: bridge
    name: sentimental-frontend

services:
  database:
    container_name: database
    image: database:development
    env_file:
      - ./services/db/.env
    expose:
      - 5432
    networks:
      - backend
    volumes:
      - ./services/db/data:/var/lib/postgresql/data/
    build:
      context: ./services/db/
      dockerfile: Dockerfile

  server:
    container_name: server
    image: server:development
    depends_on:
      - database
    env_file:
      - ./services/server/.env
    networks:
      - backend
    ports:
      - 5000:5000
    volumes:
      - ./services/server:/usr/src/app
      - ./services/server/logs:/var/log
      - ./services/server/migrations:/usr/src/app/migrations
    build:
      context: ./services/server/
      dockerfile: Dockerfile

  client:
    container_name: client
    image: client:development
    depends_on:
      - server
    environment:
      - NODE_ENV=development
      - PORT=80
      - REACT_APP_SERVER_URL=http://localhost:5000
    networks:
      - frontend
    ports:
      - 80:80
    volumes:
      - /usr/src/app/node_modules
    build:
      context: ./services/client/
      dockerfile: Dockerfile
