version: "3.7"

networks:
  backend:
    driver: bridge
    name: sentimental-backend

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - ./services/db/.env
    expose:
      - 5432
    networks:
      - backend
    volumes:
      - ./services/db/data:/var/lib/postgresql/data/
    build:
      context: ./services/db/
      dockerfile: Dockerfile

  server:
    container_name: server
    image: server
    depends_on:
      - postgres
    env_file:
      - ./services/server/.env
    networks:
      - backend
    ports:
      - 8000:5000
    volumes:
      - ./services/server:/usr/src/app
    build:
      context: ./services/server/
      dockerfile: dev.Dockerfile
