"""Adds user id in token schema

Revision ID: 003
Revises: 002
Create Date: 2020-06-15 19:18:25.699526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_column('tokens', 'user_id')
    # ### end Alembic commands ###
