name: greetings

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install pipenv
          pipenv lock --dev --requirements > ./requirements.txt
          pip install --requirement requirements.txt

      - name: Run black
        run: |
          black --check --config services/server/pyproject.toml services/server
